backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

slug: { encoding: ascii, clean_accents: true }

collections:
  - name: articles
    label: Bài viết
    folder: static/articles
    create: true
    fields:
      - { name: title, label: Tiêu đề }
      - { name: description, label: Mô tả ngắn, widget: text }
      - { name: tag, label: Thẻ bài viết, widget: string}
      - { name: thumbnail, label: Ảnh bìa, widget: image }
      - { name: body, label: Nội dung, widget: markdown }
      - { name: date, label: Ngày đăng, widget: date, format: MM-DD-YYYY }
